### ISSUE TITLE
Create your LinkFree! #Hacktoberfest

### ISSUE THREAD

**Issue by MichaelBarney** [MichaelBarney/LinkFree#2]
Create your LinkFree, add it to your Instagram account and share it with the community!

**Comment by shiven7734** [comment]
Please assign i want to add a Red zone

**Comment by marianabeldi** [comment]
Hi! Added a new theme #103

**Comment by 0nikhilkumar** [comment]
Sir I am hacktoberfest'23 participants so please merge this Pull Request and give the label of "hacktoberfest-accepted" then its counted for merging 1PR in hacktoberfest'23 event.  @MichaelBarney
