### ISSUE TITLE
Create a LinkFree template! #Hacktober

### ISSUE THREAD

**Issue by MichaelBarney** [MichaelBarney/LinkFree#3]
Create your own LinkFree template for many other users to use!

**Comment by ashusengar** [comment]
Hey @MichaelBarney is the opportunity still open

**Comment by MichaelBarney** [comment]
Of course! Let's create awesome templates!

**Comment by Noevenzahn** [comment]
@Mohit-Aasirwal As you probably noticed, the project owner isn't quite active here at the moment. So it's unclear if your PR will be accepted. Fingers crossed!

**Comment by MichaelBarney** [comment]
> @MichaelBarney Is this issue open for this year's hacktoberfest?

> @Mohit-Aasirwal As you probably noticed, the project owner isn't quite active here at the moment. So it's unclear if your PR will be accepted. Fingers crossed!

The issue will be open and I will be focusing on accepting pull requests. Happy Hacktober!

**Comment by marianabeldi** [comment]
Hi! I added a new theme :) #104

**Comment by rtdev-com** [comment]
Fixed two links in #105. Also started a [new repo](https://github.com/rtdev-com/kiwilink) for anyone wanting to hosting their personal LinkFree 😃

**Comment by Srigopalsarda** [comment]
I updated the business theme to make it more appealing to users. #115
