### ISSUE TITLE
Adding another site

### ISSUE THREAD

**Issue by avipars** [MichaelBarney/LinkFree#32]
Thank you for making this template ;) 

I would just like to point out that the userProfile should be 600x600 pixels to get best results. 

And I just used your template to make my own profile: 
https://www.aviparshan.com/israeldeals/index.html

It would be awesome if you could add me to the users file ;)

**Comment by MichaelBarney** [comment]
Sure thing avipars!

You can go ahead and make the changes in a Pull Request

**Comment by avipars** [comment]
Will do
