### ISSUE TITLE
Display Picture cuts in Abstract template if more than 4 links are added...

### ISSUE THREAD

**Issue by akshansh-s** [MichaelBarney/LinkFree#77]
![image](https://user-images.githubusercontent.com/36948805/137003426-18c48f59-99e3-4142-a323-da38403ea681.png)
I added about 6 links on my website and it cuts my image in some devices and screen resolutions...
I think this can be fixed with CSS, please have a look at it :D
Template- Abstract.

**Comment by Noevenzahn** [comment]
Hey! @akshansh-s 
Seems like the main problem is, that the height of the `<body>` is set to 100vh to properly center the card with flexbox. If you delete that line and put some margin (top and bottom)  on the `<main>` tag, it should work as expected, even with more links added.

**Comment by akshansh-s** [comment]
Thanks @Noevenzahn , it worked for me :D
