### ISSUE TITLE
Removing google fonts

### ISSUE THREAD

**Issue by Kreuger** [MichaelBarney/LinkFree#93]
Hey I dont want to use the google fonts on my page. Is it ok to just erase that from the header?

**Comment by Noevenzahn** [comment]
Sure! The templates are here to be customized to your needs. If you want to change anything, feel free to do so!

**Comment by Kreuger** [comment]
Thanks!

**Comment by Noevenzahn** [comment]
If you've got a repository or CodePen, so I can look into the code, I might be able to help!

**Comment by Kreuger** [comment]
Yeah I made one from the template here. You should be able to see it from my profile.

**Comment by Noevenzahn** [comment]
Hey, the two icons are just missing the `.fab` class — which adds some `margin-top`, so everything is centered.

**Comment by Kreuger** [comment]
I will look at that later today. Thanks.

**Comment by Kreuger** [comment]
So when I change the one for disqus, it no longer loads the icon but it worked fine for Mastodon. Here is how I made the class. 

` <i class="fab fa-solid fa-comments fa-xl"></i>`

**Comment by Noevenzahn** [comment]
Maybe something weird going on with the cache? If I open your deployment, only Disqus is missing the `fab` class, everything else works as expected. If I add the class via the devtools, the Disqus one aligns properly, too.

**Comment by Kreuger** [comment]
Not sure what Im doing wrong but when I edited the page and then opened the link it didnt change. When I specify the index.html page in the URL it positions fine but the icon is blank.

**Comment by Noevenzahn** [comment]
Weird. Don't know what it could be, either.

**Comment by Kreuger** [comment]
Thanks anyways. I guess I should close this issue.
